### ISSUE TITLE
Fix CFG API

### ISSUE THREAD

**Issue by montyly** [trailofbits/evm_cfg_builder#14]
We currently have a mix between the properties and the functions of the [CFG](https://github.com/trailofbits/evm_cfg_builder/blob/master/evm_cfg_builder/cfg/__init__.py).
What we should have:
- `cfg.instructions`/`cfg.basic_blocks`/`cfg.functions` properties returning a list
- `cfg.get_instruction_at(addr)`/`cfg.get_basic_block_at(addr)`/`cfg.get_function_at(addr)` functions returning the element
- remove the `.._from_addr` properties

**Comment by joshwatson** [comment]
Fixed in PR #15
